### ISSUE TITLE
CSS Stats is down

### ISSUE THREAD

**Issue by joshuadiablito** [cssstats/cssstats#265]
https://cssstats.com/ deployment not found :(

**Comment by j9t** [comment]
@mrmrs, @johno, @jxnblk, is there anything major to help with? I’d be open to discuss funding or infrastructure support if that’s needed.

**Comment by alex-page** [comment]
It is back online.

**Comment by johno** [comment]
Yeah, this was my bad when doing some moving around of the domain between teams. Didn't realize the deployment wouldn't follow along 😬 🙃 

It should all be back online now and you can expect a few rad updates this week as we brush off the cobwebs after some much needed spring cleaning.

> is there anything major to help with? I’d be open to discuss funding or infrastructure support if that’s needed.

Thanks for offering @j9t! With the latest updates I've gotten hosting down to a few dollars a month so we don't really need financial support. But we could always use dev help, feature suggestions, or sharing the project!

---

Going to close this now since I've got the deployments/teams/etc all resolved.
